/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    getBoard
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Main_getBoard
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    makeMovement
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_Main_makeMovement
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     Main
 * Method:    gameOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Main_gameOver
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getNextPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_getNextPlayer
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getDimension
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_Main_getDimension
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     Main
 * Method:    getPlayerValue
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_getPlayerValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    setBoardSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_setBoardSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    gameKeyReader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Main_gameKeyReader
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    placeMark
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_placeMark
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    getCursorRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_getCursorRow
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getCursorColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_getCursorColumn
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    moveCursor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_moveCursor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
